version: '3.1'
services:
  mongo:
    image: 'mongo:6.0.8'
    restart: 'always'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'pass'
    ports:
      - '5431:27017'

  postgres:
    image: postgres:16.1
    environment:
      - 'POSTGRES_DB=orderservice'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'

  inventoryService:
    image: postgres:16.1
    environment:
      - 'POSTGRES_DB=inventoryservice'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=root'
    ports:
      - '5433:5432'
